version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: tutoring_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tutoring_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tutoring_network

  # Express API
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tutoring_api
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DB_USER: postgres
      DB_PASSWORD: password
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: tutoring_db
      JWT_SECRET: dev-secret-key-change-in-production
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - tutoring_network

volumes:
  postgres_data:

networks:
  tutoring_network:
    driver: bridge
